Update the request object with sensible defaults and access methods, #13
sendgrid/java-http-client pull request #15
Opened 2016-10-05 06:58 UTC by belfazt

2016-10-05 16:43 UTC, thinkingserious requested changes

2016-10-05 16:43 UTC, thinkingserious commented on examples/Example.java
> +    request.getHeaders().put("Authorization", "Bearer " + System.getenv("SENDGRID_API_KEY"));
Can we use a setter here instead?

e.g. `request.addHeader("Authorization", "Bearer " + System.getenv("SENDGRID_API_KEY"));`

2016-10-05 16:43 UTC, thinkingserious commented on examples/Example.java
> +    request.getQueryParams().put("offset", "0");
Can we use a setter here instead?

e.g. `request.addQueryParam("offset", "0");`

2016-10-05 16:43 UTC, thinkingserious commented on examples/Example.java
> +    request.getQueryParams().clear();
How about `request.clearQueryParams();`

2016-10-05 17:48 UTC, belfazt commented
Will update it later tonight! Thanks for the feedback

2016-10-06 04:12 UTC, belfazt commented on examples/Example.java
> +    request.getHeaders().put("Authorization", "Bearer " + System.getenv("SENDGRID_API_KEY"));
fixed

2016-10-06 04:12 UTC, belfazt commented on examples/Example.java
> +    request.getQueryParams().put("offset", "0");
fixed

2016-10-06 04:12 UTC, diegoc-am commented on examples/Example.java
> +    request.getQueryParams().clear();
fixed

2016-10-06 04:16 UTC, belfazt commented
fixed!

2016-10-07 02:23 UTC, thinkingserious approved these changes

2016-10-07 02:27 UTC, merged