Assign server response outside try block
sendgrid/java-http-client pull request #17
Opened 2016-10-27 06:33 UTC by bluestealth

An attempt to fix [Sendgrid client doesn't close TCP connection properly #165](https://github.com/sendgrid/sendgrid-java/issues/165).

2016-10-27 19:19 UTC, thinkingserious commented
Hello @bluestealth,

Thanks for the PR!

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/java-http-client/blob/master/CONTRIBUTING.md#cla) so we can review?

2016-10-27 20:50 UTC, thinkingserious commented on src/main/java/com/sendgrid/Client.java
> +		CloseableHttpResponse serverResponse = httpClient.execute(httpPost);
I don't understand how this fixes https://github.com/sendgrid/sendgrid-java/issues/165. It seems like the original code should be closing the connection at the end. Could you please elaborate on how your solution fixes the issue?

Some other questions:
1. Did you test this? If so, could you describe them? I'd like to reproduce.
2. By moving the `httpClient.execute` out of the try/catch/finally, how will we handle any exceptions at that function call.

Thanks!

2016-10-28 03:07 UTC, bluestealth commented on src/main/java/com/sendgrid/Client.java
> +		CloseableHttpResponse serverResponse = httpClient.execute(httpPost);
You are correct that this doesn't fix the error, and could result in some exceptional states not being caught, but I can imagine some sequence of events where serverResponse.close() isn't called with the existing code. Give me a bit to think about that.

With this finalizer as long as the client nulls their reference to Class SendGrid or the class goes out of scope the port should be released. I have tested this on my own machine by nulling my reference, forcing garbage collection and then busy waiting to keep the process open.

```java
	@Override
	public void finalize() throws Throwable {
		try {
			this.httpClient.close();
		} catch(IOException e) {
			throw new Throwable(e.getMessage());
		} finally {
			super.finalize();
		}
	}
```

2016-10-28 15:47 UTC, thinkingserious commented on src/main/java/com/sendgrid/Client.java
> +		CloseableHttpResponse serverResponse = httpClient.execute(httpPost);
Thanks for the follow up!

I'm not quite sure what is going on here, but I plan to investigate further.

2017-03-04 04:13 UTC, thinkingserious requested changes

2017-03-04 04:13 UTC, thinkingserious commented on build.gradle
> +apply plugin: "eu.appsatori.fatjar"
It looks like this plugin is no longer under development, per: https://github.com/musketyr/gradle-fatjar-plugin

Do you mind converting to https://github.com/johnrengelman/shadow?

2017-03-09 18:05 UTC, thinkingserious approved these changes

2017-03-09 18:06 UTC, merged

2017-03-09 18:07 UTC, thinkingserious commented
@bluestealth,

Thanks again for your support! Please take a moment to fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so that we send you some swag :)