do not close or manage lifecycle of http-client passed in
sendgrid/java-http-client pull request #25
Opened 2017-10-04 21:03 UTC by maxxedev

2017-10-04 21:04 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/java-http-client?pullRequest=25) it.</sub>

2017-10-12 02:24 UTC, andy-trimble requested changes
Please add documentation to the `Client(CloseableHttpClient httpClient)` constructor indicating that the client will not be closed on finalization.

2017-10-12 02:24 UTC, andy-trimble commented on src/main/java/com/sendgrid/Client.java
> +	private boolean createdHttpClient;
Set default value to `false`

2017-10-12 03:58 UTC, andy-trimble commented on src/main/java/com/sendgrid/Client.java
> +	private boolean createdHttpClient;
Disregard this comment. The default value will be false. That is sufficient.

2017-10-12 18:08 UTC, andy-trimble approved these changes

2017-10-12 18:08 UTC, andy-trimble commented
LGTM

2017-10-27 22:02 UTC, maxxedev commented
could this be merged please?

2017-10-31 19:52 UTC, thinkingserious commented
@maxxedev,

LGTM

Please fix the conflict and I'll merge this :)

Thanks!

With Best Regards,

Elmer

2017-10-31 21:32 UTC, maxxedev commented
ah conflicts. 
fixed now.

2017-10-31 22:53 UTC, merged

2017-10-31 22:53 UTC, thinkingserious commented
Hello @maxxedev,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX